### ISSUE TITLE
Windows: target dependency with a large number of .swift files can fail to build

### ISSUE THREAD

**Issue by gregcotten** [apple/swift-package-manager#5927]
### Description

Example project here:
https://github.com/gregcotten/example-spm-compile-error

# Details
I made a [fork](https://github.com/gregcotten/swift-com/tree/example-spm-compile-error) of  [SwiftCOM](https://github.com/compnerd/swift-com) and removed the `.dynamic` requirement of the vended library. My intent was to make a *larger* single dynamic library with that code packaged in so I didn't have to deal with multiple .dlls.

## The Real Issue
There are just too many swift files in the target dependency for the compiler to handle, I think. I made another branch of SwiftCOM (just change branch name from `example-spm-compile-error` to `develop`) with less files in the target that can build in release mode just fine! The first hint I got was when I used the flag `--use-integrated-swift-driver` and saw some error about the path being too long. 

## To Reproduce the Bug
Tested on Windows 10 + Swift 5.7.1

Clone the example repo and run `swift build -c release`

### Expected Result
The build finishes without errors

### Actual Result
Error:
`<unknown>:0: error: supplementary output file map 'C:\\Users\\gregc\\AppData\\Local\\Temp\\TemporaryDirectory.aUcYOo\\supplementaryOutputs-1' is missing an entry for 'C:\\Users\\gregc\\Documents\\GitHub\\example-spm-compile-error\\.build\\checkouts\\swift-com\\Sources\\SwiftCOM\\COMBase.swift' (this likely indicates a compiler issue; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project)`

### Swift Package Manager version/commit hash

5.7.1

### Swift & OS version (output of `swift --version && uname -a`)

compnerd.org Swift version 5.7.1 (swift-5.7.1-RELEASE)
Target: x86_64-unknown-windows-msvc

Windows 10

**Comment by neonichu** [comment]
cc @compnerd

**Comment by compnerd** [comment]
Hmm, this would be an issue in the swift-driver right?  Or is the OFM written by SPM?

**Comment by gregcotten** [comment]
Wasn't sure where to post the issue, please point me to the right place and I'll move it there!

**Comment by compnerd** [comment]
CC: @artemcm

**Comment by artemcm** [comment]
OFM *is* written by SPM:
https://github.com/apple/swift-package-manager/blob/main/Sources/Build/BuildPlan.swift#L1093

But I'm not sure why some source file may be missing, I've not seen that before.

**Comment by lemonmojo** [comment]
@artemcm @compnerd We just ran into this as well using the Swift 5.10.1 toolchain for Windows on Github Actions. We have a project which wraps [FreeRDP](https://github.com/freerdp/freerdp) (a large OS project written in C). The number of Swift source files is around 130 at the moment but there's lots of C header files that get imported through unsafe flags in the SPM project. Currently, those amount to around 250.

The issue came up recently when a new swift file was added. After we saw the compiler error on CI, we merged a couple of types into a single file which resolves the issue for now. But now we're in the unfortunate state where we have to worry about breaking compilation on Windows every time a new file is added. Right now we have 4 to go before we hit the ceiling again.

**Comment by gregcotten** [comment]
@compnerd I ran into this on release 6.0.1 on Windows. Do you have any recommendations?

**Comment by compnerd** [comment]
Try using main, I believe that the issue itself has been resolved in swift-driver, but we might've failed to backport it.

**Comment by gregcotten** [comment]
> Try using main, I believe that the issue itself has been resolved in swift-driver, but we might've failed to backport it.

I'll give `main` a try. In the meantime, passing `--use-integrated-swift-driver` seems to do the trick.

**Comment by gregcotten** [comment]
> Try using main, I believe that the issue itself has been resolved in swift-driver, but we might've failed to backport it.

OK tried it on a (main snapshot?) [TBC build from yesterday](https://github.com/thebrowsercompany/swift-build/releases/tag/20241012.3) and still have the same issue.
